
package com.haier.hailian.contract.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CreateChainGroup", targetNamespace = "http://xmlns.oracle.com/Interface/CreateChainGroup")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CreateChainGroup {


    /**
     * 
     * @param inCHAINCODE
     * @param outCHAINCODE
     * @param inISTPT
     * @param inCHAINATTR
     * @param outCHAINGROUPCODE
     * @param retmsg
     * @param inMANAGER
     * @param inSUBCLASS
     * @param inSUBCLASSMANAGERNO
     * @param createdBY
     * @param inCHAINNAME
     * @param inMAJORCLASS
     * @param inSHORTNAME
     * @param inCHAINMANAGERNO
     * @param retcode
     */
    @WebMethod(action = "process")
    @RequestWrapper(localName = "process", targetNamespace = "http://xmlns.oracle.com/Interface/CreateChainGroup", className = "com.spring.webService.ws.Process")
    @ResponseWrapper(localName = "processResponse", targetNamespace = "http://xmlns.oracle.com/Interface/CreateChainGroup", className = "com.spring.webService.ws.ProcessResponse")
    public void process(
            @WebParam(name = "IN_CHAIN_CODE", targetNamespace = "http://xmlns.oracle.com/Interface/CreateChainGroup")
                    String inCHAINCODE,
            @WebParam(name = "IN_CHAIN_NAME", targetNamespace = "http://xmlns.oracle.com/Interface/CreateChainGroup")
                    String inCHAINNAME,
            @WebParam(name = "IN_MAJOR_CLASS", targetNamespace = "http://xmlns.oracle.com/Interface/CreateChainGroup")
                    String inMAJORCLASS,
            @WebParam(name = "IN_SUB_CLASS", targetNamespace = "http://xmlns.oracle.com/Interface/CreateChainGroup")
                    String inSUBCLASS,
            @WebParam(name = "IN_CHAIN_ATTR", targetNamespace = "http://xmlns.oracle.com/Interface/CreateChainGroup")
                    String inCHAINATTR,
            @WebParam(name = "IN_SHORT_NAME", targetNamespace = "http://xmlns.oracle.com/Interface/CreateChainGroup")
                    String inSHORTNAME,
            @WebParam(name = "IN_IS_TPT", targetNamespace = "http://xmlns.oracle.com/Interface/CreateChainGroup")
                    String inISTPT,
            @WebParam(name = "IN_MANAGER", targetNamespace = "http://xmlns.oracle.com/Interface/CreateChainGroup")
                    String inMANAGER,
            @WebParam(name = "IN_SUB_CLASS_MANAGER_NO", targetNamespace = "http://xmlns.oracle.com/Interface/CreateChainGroup")
                    String inSUBCLASSMANAGERNO,
            @WebParam(name = "IN_CHAIN_MANAGER_NO", targetNamespace = "http://xmlns.oracle.com/Interface/CreateChainGroup")
                    String inCHAINMANAGERNO,
            @WebParam(name = "CREATED_BY", targetNamespace = "http://xmlns.oracle.com/Interface/CreateChainGroup")
                    String createdBY,
            @WebParam(name = "RETCODE", targetNamespace = "http://xmlns.oracle.com/Interface/CreateChainGroup", mode = WebParam.Mode.OUT)
                    Holder<String> retcode,
            @WebParam(name = "RETMSG", targetNamespace = "http://xmlns.oracle.com/Interface/CreateChainGroup", mode = WebParam.Mode.OUT)
                    Holder<String> retmsg,
            @WebParam(name = "OUT_CHAIN_CODE", targetNamespace = "http://xmlns.oracle.com/Interface/CreateChainGroup", mode = WebParam.Mode.OUT)
                    Holder<String> outCHAINCODE,
            @WebParam(name = "OUT_CHAIN_GROUP_CODE", targetNamespace = "http://xmlns.oracle.com/Interface/CreateChainGroup", mode = WebParam.Mode.OUT)
                    Holder<String> outCHAINGROUPCODE);

}
